force-app/main/default/objects/endpoint__mdt/fields/env__c.field-meta.xml
<CustomField>
    <fullName>env__c</fullName>
    <label>env</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>dev</fullName>
                <default>true</default>
                <label>dev</label>
            </value>
            <value>
                <fullName>prod</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/environment__mdt/environment__mdt.object-meta.xml
<CustomObject>
    <label>environment</label>
    <pluralLabel>environments</pluralLabel>
</CustomObject>

force-app/main/default/objects/environment__mdt/fields/host__c.field-meta.xml
<CustomField>
    <fullName>host__c</fullName>
    <label>host</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ETC_Callout.cls
public virtual with sharing class ETC_Callout {
	public endpoint__mdt mdt;
	public environment__mdt env;
	public String claseApex;

	public class Callout {
		public Http http;
		public HttpRequest request;
		public HttpResponse response;
		public Callout(Http http, HttpRequest request, HttpResponse response) {
			this.http = http;
			this.request = request;
			this.response = response;
		}
	}

	public ETC_Callout() {
	}

	public ETC_Callout(String metadataName) {
		this.mdt = ETC_Utility.getEndpoint(metadataName);
		this.env = ETC_Utility.getEnv(mdt.env__c);
	}

	public virtual Callout createCallout(String metadataName, String queries) {
		endpoint__mdt mdt = this.mdt != null ? this.mdt : ETC_Utility.getEndpoint(metadataName);
		environment__mdt env =  this.env != null ? this.env : ETC_Utility.getEnv(this.mdt.env__c);

		this.mdt = mdt;
		this.env = env;

		Http http = new Http();
		HttpRequest request = new HttpRequest();
		HttpResponse response = new HttpResponse();

		String endpoint = env.host__c + mdt.endpoint__c;
		if (queries != null) {
			endpoint += queries;
		}
		
		request.setEndpoint(endpoint);
		request.setMethod(mdt.method__c);
		request.setHeader('Accept-Encoding', 'gzip, deflate, br');
		request.setHeader('Accept', '*/*');
		request.setHeader('Content-Type', 'application/json');
		request.setHeader('User-Agent', 'Salesforce');
		request.setHeader('Connection', 'Keep-Alive');
		// request.setCompressed(true);
		request.setTimeout(120000);
		return new Callout(http, request, response);
	}

	public virtual HttpResponse sendCallout(Callout callout) {
		callout.response = new HttpResponse();
		if (!Test.isRunningTest()) {
			callout.response = callout.http.send(callout.request);
		}
		return callout.response;
	}
}